// Code generated by entc, DO NOT EDIT.

package db

import (
	"time"

	"github.com/NickDubelman/fantasy-bball/db/schema"
	"github.com/NickDubelman/fantasy-bball/db/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescJoined is the schema descriptor for joined field.
	userDescJoined := userFields[3].Descriptor()
	// user.DefaultJoined holds the default value on creation for the joined field.
	user.DefaultJoined = userDescJoined.Default.(func() time.Time)
	// userDescLastActive is the schema descriptor for lastActive field.
	userDescLastActive := userFields[4].Descriptor()
	// user.DefaultLastActive holds the default value on creation for the lastActive field.
	user.DefaultLastActive = userDescLastActive.Default.(func() time.Time)
}
