// Code generated by entc, DO NOT EDIT.

package user

import (
	"time"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPicture holds the string denoting the picture field in the database.
	FieldPicture = "picture"
	// FieldJoined holds the string denoting the joined field in the database.
	FieldJoined = "joined"
	// FieldLastActive holds the string denoting the lastactive field in the database.
	FieldLastActive = "last_active"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPicture,
	FieldJoined,
	FieldLastActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultJoined holds the default value on creation for the "joined" field.
	DefaultJoined func() time.Time
	// DefaultLastActive holds the default value on creation for the "lastActive" field.
	DefaultLastActive func() time.Time
)
